name        'devpi-puppet'
version     '0.3.0'
source      'git://github.com/jhermann/devpi-puppet.git'
author      'Jürgen Hermann'
summary     'Module to install the devpi local PyPI proxy and repository'
description 'Install and manage devpi-server'
license     'Apache License, Version 2.0'
