name        'devpi-puppet'
version     '0.1.0'
source      'git://github.com/jhermann/devpi-puppet.git'
author      'Jürgen Hermann'
summary     'Module to install the devpi PyPI local proxy and repository'
description 'Install and manage devpi-server'
license     'Apache License, Version 2.0'
